version: '3.9'

services:

  some-rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    depends_on:
      - db
      - some-rabbit
    build: ./file_handler
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  celery:
    depends_on:
      - db
      - some-rabbit
    build: ./file_handler
    command: bash -c "celery -A file_handler worker -l INFO"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    
  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./file_handler/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  postgres_data:
  static_value:
  media_value:
