# Generated by Django 4.2.6 on 2023-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Время загрузки')),
                ('processed', models.BooleanField(verbose_name='Обработка')),
            ],
        ),
    ]
