# Generated by Django 4.2.6 on 2023-11-03 14:43

from django.db import migrations, models
import files.storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=files.storage.MyStorage(), upload_to='uploaded_files/', verbose_name='Имя файла'),
        ),
    ]
