# Generated by Django 4.2.6 on 2023-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработка'),
        ),
    ]
